version: "3.8"

services:
    mongodb:
        image: mongo:4.4.4
        container_name: mongodb
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=rootpass
        volumes:
            - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
            - mongodb-data:/data/db
        networks:
            - mongodb_network
        ports:
            - 27017:27017
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
            interval: 30s
            timeout: 10s
            retries: 3
        restart: unless-stopped
    mongo-express:
        image: mongo-express:0.54.0
        container_name: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongodb
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=admin123
        volumes:
            - mongodb-data
        depends_on:
            - mongodb
        networks:
            - mongodb_network
        ports:
            - 8081:8081
        healthcheck:
            test:  wget --quiet --tries=3 --spider http://admin:admin123@localhost:8081 || exit 1
            interval: 30s
            timeout: 10s
            retries: 3
        restart: unless-stopped
    django:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        environment:
            - ENVIRONMENT=production
        networks:
            - mongodb_network
        depends_on:
            - mongodb

volumes:
    mongodb-data:
        name: mongodb-data

networks:
    mongodb_network:
        name: mongodb_network