# Generated by Django 3.0.5 on 2021-04-07 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(choices=[('CN', 'Costa Nova'), ('BA', 'Barra'), ('RA', 'Ria Ativa'), ('DN', 'Duna'), ('PT', 'Ponte Barra'), ('25', 'A25 Aveiro')], max_length=2)),
                ('event_type', models.CharField(choices=[('RT', 'Road Traffic'), ('RD', 'Road Danger'), ('BL', 'Bike Lanes'), ('CO', 'Conditions'), ('CF', 'Carbon Footprint')], max_length=2)),
                ('event_class', models.CharField(choices=[('AN', 'Animal'), ('PE', 'Person'), ('SO', 'Strange Object'), ('SC', 'Stopped Car'), ('CA', 'Car'), ('BC', 'Bicycle'), ('MC', 'Motorcycle'), ('TR', 'Truck'), ('RA', 'Rain'), ('FO', 'Fog'), ('NL', 'No light'), ('CS', 'Car Speeding')], max_length=2, null=True)),
                ('velocity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(-300)])),
                ('latitude', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180)])),
                ('co2km', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
