# Generated by Django 3.0.5 on 2021-04-14 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('CN', 'Costa Nova'), ('BA', 'Barra')], max_length=2)),
                ('condition', models.CharField(choices=[('FG', 'Fog'), ('CL', 'Clean'), ('RN', 'Rain')], max_length=2)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('daytime', models.BooleanField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DailyInflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('CN', 'Costa Nova'), ('BA', 'Barra')], max_length=2)),
                ('maximum', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('current', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(choices=[('CN', 'Costa Nova'), ('BA', 'Barra'), ('RA', 'Ria Ativa'), ('DN', 'Duna'), ('PT', 'Ponte Barra'), ('25', 'A25 Aveiro')], max_length=2)),
                ('event_type', models.CharField(choices=[('RT', 'Road Traffic'), ('RD', 'Road Danger'), ('BL', 'Bike Lanes'), ('CO', 'Conditions')], max_length=2)),
                ('event_class', models.CharField(choices=[('AN', 'Animal'), ('PE', 'Person'), ('SO', 'Strange Object'), ('SC', 'Stopped Car'), ('CA', 'Car'), ('BC', 'Bicycle'), ('MC', 'Motorcycle'), ('TR', 'Truck'), ('RA', 'Rain'), ('FO', 'Fog'), ('NL', 'No light'), ('LT', 'Light'), ('OT', 'Outside Temperature'), ('CS', 'Car Speeding'), ('CF', 'Carbon Footprint')], max_length=2)),
                ('velocity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(400), django.core.validators.MinValueValidator(-400)])),
                ('latitude', models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180)])),
                ('co2km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
