# Generated by Django 3.0.5 on 2021-04-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility_5g_rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_class',
            field=models.CharField(choices=[('AN', 'Animal'), ('PE', 'Person'), ('SO', 'Strange Object'), ('SC', 'Stopped Car'), ('CA', 'Car'), ('BC', 'Bicycle'), ('MC', 'Motorcycle'), ('TR', 'Truck'), ('RA', 'Rain'), ('FO', 'Fog'), ('NL', 'No light'), ('LT', 'Light'), ('OT', 'Outside Temperature'), ('CS', 'Car Speeding'), ('CF', 'Carbon Footprint')], max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('RT', 'Road Traffic'), ('RD', 'Road Danger'), ('BL', 'Bike Lanes'), ('CO', 'Conditions')], max_length=2),
        ),
    ]
