# Generated by Django 3.0.5 on 2021-04-30 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility_5g_rest_api', '0002_remove_dailyinflow_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('velocity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(400), django.core.validators.MinValueValidator(-400)])),
                ('latitude', models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180)])),
                ('radar_id', models.CharField(choices=[('DN', 'Duna'), ('RA', 'Ria Ativa'), ('PT', 'Ponte Barra')], max_length=2)),
                ('object_class', models.CharField(choices=[('CA', 'Car'), ('MB', 'Motorbike'), ('TR', 'Truck')], max_length=2)),
            ],
        ),
    ]
