# Generated by Django 3.0.5 on 2021-05-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility_5g_rest_api', '0003_radarevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='co2km',
            new_name='co2',
        ),
        migrations.AlterField(
            model_name='climate',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dailyinflow',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
