# Generated by Django 3.0.5 on 2021-06-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility_5g_rest_api', '0005_auto_20210504_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='radarevent',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='radarevent',
            name='object_class',
        ),
        migrations.AlterField(
            model_name='dailyinflow',
            name='location',
            field=models.CharField(choices=[('CN', 'Costa Nova'), ('BA', 'Barra'), ('BT', 'Both Costa Nova and Barra')], max_length=2),
        ),
        migrations.AlterField(
            model_name='radarevent',
            name='radar_id',
            field=models.CharField(choices=[('DN', 'Duna'), ('7', 'Ria Ativa'), ('PT', 'Ponte Barra')], max_length=2),
        ),
    ]
