# Generated by Django 3.0.5 on 2021-06-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility_5g_rest_api', '0007_auto_20210607_2133'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='climate',
            name='mobility_5g_locatio_eef2e8_idx',
        ),
        migrations.RemoveIndex(
            model_name='climate',
            name='mobility_5g_timesta_a85491_idx',
        ),
        migrations.RemoveIndex(
            model_name='dailyinflow',
            name='mobility_5g_locatio_96366c_idx',
        ),
        migrations.RemoveIndex(
            model_name='dailyinflow',
            name='mobility_5g_date_7bccb2_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='mobility_5g_locatio_1e84f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='mobility_5g_locatio_2ea010_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='mobility_5g_timesta_d3304c_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='mobility_5g_velocit_2128cb_idx',
        ),
        migrations.AddIndex(
            model_name='climate',
            index=models.Index(fields=['-timestamp', 'location'], name='mobility_5g_timesta_30f025_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyinflow',
            index=models.Index(fields=['-date', 'location'], name='mobility_5g_date_0eee24_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-timestamp', 'event_type', 'event_class', 'location'], name='mobility_5g_timesta_23e7b2_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-timestamp', 'event_type', 'location'], name='mobility_5g_timesta_2f0a49_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-timestamp', 'event_class', 'location'], name='mobility_5g_timesta_e7a5f1_idx'),
        ),
    ]
