# Generated by Django 3.0.5 on 2021-06-11 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility_5g_rest_api', '0009_auto_20210609_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyinflow',
            name='current',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='dailyinflow',
            name='maximum',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
