version: "3.8"

services:
    rabbitmq:
        image: rabbitmq:3.8.3-management
        container_name: rabbitmq
        restart: unless-stopped
        volumes:
            - ./definitions.json:/etc/rabbitmq/definitions.json
            - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
        ports:
            - 5672:5672
            - 15672:15672
